version: 1
formatters:
  simple:
    format: '%(message)s'
  complex:
    format: '%(levelname)-8s %(asctime)s [%(name)s; %(filename)s:%(lineno)s] %(message)s'
    datefmt: '%m-%d %H:%M:%S'
  colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(levelname)-8s%(reset)s %(asctime)s [%(name)s; %(filename)s:%(lineno)s] %(message)s'
    datefmt: '%m-%d %H:%M:%S'
    log_colors:
      DEBUG: green
      INFO: cyan
      WARNING: yellow
      ERROR: red
      CRITICAL: purple
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: complex
    filename: /home/mcv/toolbox/mcvconsoler.log
    encoding: utf-8

loggers:
  paramiko.transport:
    level: WARNING
    handlers: [console, file]

root:
  level: NOTSET
  handlers: [console, file]