version: 1
disable_existing_loggers: False
formatters:
  complex:
    format: '%(levelname)-8s %(asctime)s [%(name)s; %(filename)s:%(lineno)s] %(message)s'
    datefmt: '%m-%d %H:%M:%S'
  colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(levelname)-8s%(reset)s %(asctime)s [%(name)s; %(filename)s:%(lineno)s] %(message)s'
    datefmt: '%m-%d %H:%M:%S'
    log_colors:
      DEBUG: green
      INFO: cyan
      WARNING: yellow
      ERROR: red
      CRITICAL: purple
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: complex
    filename: /home/mcv/toolbox/mcvconsoler.log
    encoding: utf-8
# FIXME(vkaznacheiev): this handler should be dynamically added when
# the app starts and we need prevent changing the name of this handler
  mcvconsoler_current_run:
    class: logging.FileHandler
    mode: w
    level: DEBUG
    formatter: complex
    filename: /tmp/mcvconsoler.log
    encoding: utf-8

loggers:
  mcv_consoler:
    level: DEBUG
  requests:
    level: CRITICAL
  paramiko.transport:
    level: CRITICAL

root:
  level: INFO
  handlers: [console, file, mcvconsoler_current_run]
